name: Release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          target-branch: main
          # BUG: -- https://github.com/googleapis/release-please-action/issues/937
          # Set to true for automatic release without PR
          skip-github-pull-request: false
